# Generated by Django 4.1.7 on 2024-10-17 01:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_mid_tit_001', models.CharField(blank=True, max_length=100000, verbose_name='預約連結')),
                ('oc_mid_txt_001', models.CharField(blank=True, max_length=100000, verbose_name='臘腸狗圖-size:300X300px')),
                ('oc_mid_tit_002', models.CharField(blank=True, max_length=100000, verbose_name='科基圖-size:300X300px')),
                ('oc_mid_txt_002', models.CharField(blank=True, max_length=100000, verbose_name='博美圖-size:300X300px')),
                ('oc_mid_tit_003', models.CharField(blank=True, max_length=100000, verbose_name='柴犬圖-size:300X300px')),
                ('oc_mid_txt_003', models.CharField(blank=True, max_length=100000, verbose_name='吉娃娃圖-size:300X300px')),
                ('oc_mid_tit_004', models.CharField(blank=True, max_length=100000, verbose_name='雪納瑞圖-size:300X300px')),
                ('oc_dog_ctn_001', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='注意事項')),
                ('oc_dog_ctn_002', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='小美容')),
                ('oc_dog_ctn_003', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='大美容')),
                ('oc_dog_ctn_004', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='額外服務')),
                ('oc_dog_ctn_005', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='獲獎事項')),
                ('oc_dog_ctn_006', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='專業證照')),
                ('oc_dog_ph_001', models.CharField(blank=True, max_length=100000, verbose_name='獎項證照圖-1')),
                ('oc_dog_ph_002', models.CharField(blank=True, max_length=100000, verbose_name='獎項證照圖-2')),
                ('oc_dog_ph_003', models.CharField(blank=True, max_length=100000, verbose_name='獎項證照圖-3')),
                ('oc_dog_ph_004', models.CharField(blank=True, max_length=100000, verbose_name='獎項證照圖-4')),
                ('oc_dog_line', models.CharField(blank=True, max_length=100000, verbose_name='LINE連結')),
                ('oc_dog_mail', models.CharField(blank=True, max_length=100000, verbose_name='信箱')),
                ('oc_dog_phone', models.CharField(blank=True, max_length=100000, verbose_name='電話')),
                ('oc_dog_adr', models.CharField(blank=True, max_length=100000, verbose_name='地址')),
                ('oc_dog_fb', models.CharField(blank=True, max_length=100000, verbose_name='Facebook')),
                ('oc_dog_ig', models.CharField(blank=True, max_length=100000, verbose_name='instagram')),
            ],
            options={
                'verbose_name': '首頁',
                'verbose_name_plural': '首頁',
            },
        ),
    ]
